### PR TITLE
Add some test depth

### PR DESCRIPTION
**Pull request by ckormanyos**
Hi @imahjoub this PR adds some test depth and some other details (such as preserving the flags on `std::cout`). I also tried to rework some of the flags used in coverage such that more template instantiations and ctors/dtors sre reflected in the coverage.

I also reduced the optimization during the code coverage run to `-O1` in order to get reduce discrepancies between coverage reporting and the written code.

All in all, the coverage increases. This stuff is, however, all optional. See if you like som, any, noe or all of these changes.

For the moment, the SONAR checks do not run on my cloned repo. Let's see if they run in the official PR...

### CODE REVIEW

**Comment by ckormanyos** [comment]
I think can see why the diff hit coverage fails with 0 percent. I changed only 1 line of code. It was being hit before the PR and is still being hit after the PR. I also did put one `lcov`exclude on the `constexpr` default dtor. Maybe this explaing the diff hit of 0.

Anyway that's not critical.

What really strikes me as unusual is why I'm not able to upload SONAR analyses. I've had this same problem on some of my own repos from contributors, and I never found the way to solve it. I'm not sure if it's in the admin settings on the forked repo or on the admin settings of original (your) repo or in the admin settings of the SONAR.

**Comment by ckormanyos** [comment]
Hi Iliass. Well if I use my own sonar properties, then the SONAR analysis is [successful](https://github.com/ckormanyos/pi_spigot/actions/runs/2563656759).

But this does not really include exactly what's desired here because I have modified my local (forked) copy of [sonar-project.properties](https://github.com/ckormanyos/pi_spigot/blob/main/sonar-project.properties) in my branch of the fork.

I still do not know how I can (as a contributor) get SONAR analysis in your the PR for your repo. I've also had trouble with this in the past in my own  repos. Put it on the bit TODO list of open points I guess...

**Comment by imahjoub** [comment]
Hi @ckormanyos,

unfortunately I can not merge it directly because (build fails also in my repo), I will merge your changes manually.

This is what I got from the sonar log (see picture below), 

image

I also had that problem before and that was **because I didn't set tokens for the projects**

we can probably use the solution here -> https://community.sonarsource.com/t/how-to-use-sonarcloud-with-a-forked-repository-on-github/7363/30

**Comment by ckormanyos** [comment]
Hi @imahjoub 

Thanks for your clear responses.

> had that problem before and that was **because I didn't set tokens for the projects**

True. I've now set my tokens. But I can not run on your pipeline(s) with my tokens. The solution you mentioned above is deep, but fascinating. Seems like a cool thing to try if time allows...

My final comment regards [this line](https://github.com/ckormanyos/pi_spigot/blob/e3b5485dc2b89cc55de7e01d33fb8ffd1b2be7eb/pi_spigot/pi_spigot.h#L333), which is now the only line with 1 single miss in branch coverage.

I was not able to figure out exactly which branch condition is or was failing on that line. I actzually think (but I'm not sure) the maybe `LCOV_EXCL_LINE` would be OK for that line because it is (from a particular point of view) actually test code, independent of the algorithmic code. It's your choice!

**Comment by ckormanyos** [comment]
Hi @imahjoub I've had [this kind of thing](https://sonarcloud.io/summary/new_code?id=imahjoub_pi_spigot) before.

You need to go to your Sonar Administration panel and deactivate coverage for SONAR. Alternatively, SONAR can read reports from LCOV, but I have only heard about that, never actually done it myself.

**Comment by ckormanyos** [comment]
The SONAR code coverage settings are in your project Administration Area under the section of "Analysis Scope". I've always simply set the required gate on coverage in SONAR to 0.0% since i do not (yet) know how to upload a real coverage report (such as from LCOV) to SONAR. But it would be really cool to learn this as well...

**Comment by imahjoub** [comment]
this pull request has been replaced by https://github.com/imahjoub/pi_spigot/pull/39

**Comment by imahjoub** [comment]
Hi @ckormanyos,

Thank you for this tip, I just created a new quality gate for sonar, it is the same as the standard one without code coverage.

image

**Yes we will figure out how to integrate external code coverage into sonar, I will look into that.**

I don't know if that helps. I also gave all privileges to all members (we) for the repo in Sonar. (see picture below)

image


Many Thanks :)

**Pull request closed without merging**
